mkdir -p /var/lib/mpd/music/SDCARD/"Dua Lipa"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Dua Lipa"/"Dua Lipa - Don't Start Now.mp3" /var/lib/mpd/music/SDCARD/"Dua Lipa"
mkdir -p /var/lib/mpd/music/SDCARD/"Blind Melon"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Blind Melon"/"Blind Melon - No Rain.mp3" /var/lib/mpd/music/SDCARD/"Blind Melon"
mkdir -p /var/lib/mpd/music/SDCARD/"Michael McDonald"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Michael McDonald"/"Michael McDonald - I Keep Forgettin' (Every Time You're Near).mp3" /var/lib/mpd/music/SDCARD/"Michael McDonald"
mkdir -p /var/lib/mpd/music/SDCARD/"Lizzo"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Lizzo"/"Lizzo - Good As Hell.mp3" /var/lib/mpd/music/SDCARD/"Lizzo"
mkdir -p /var/lib/mpd/music/SDCARD/"U2"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"U2"/"U2 - With Or Without You.mp3" /var/lib/mpd/music/SDCARD/"U2"
mkdir -p /var/lib/mpd/music/SDCARD/"The Beach Boys"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Beach Boys"/"The Beach Boys - Kokomo.mp3" /var/lib/mpd/music/SDCARD/"The Beach Boys"
mkdir -p /var/lib/mpd/music/SDCARD/"Steely Dan"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Steely Dan"/"Steely Dan - Hey Nineteen.mp3" /var/lib/mpd/music/SDCARD/"Steely Dan"
mkdir -p /var/lib/mpd/music/SDCARD/"U2"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"U2"/"U2 - Where the Streets Have No Name.mp3" /var/lib/mpd/music/SDCARD/"U2"
mkdir -p /var/lib/mpd/music/SDCARD/"Timbaland"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Timbaland"/"Timbaland - Apologize.mp3" /var/lib/mpd/music/SDCARD/"Timbaland"
mkdir -p /var/lib/mpd/music/SDCARD/"The Police"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Police"/"The Police - Walking On The Moon.mp3" /var/lib/mpd/music/SDCARD/"The Police"
mkdir -p /var/lib/mpd/music/SDCARD/"Gotye"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Gotye"/"Gotye - Somebody That I Used To Know featuring Kimbra.mp3" /var/lib/mpd/music/SDCARD/"Gotye"
mkdir -p /var/lib/mpd/music/SDCARD/"Christopher Cross"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Christopher Cross"/"Christopher Cross - Ride Like The Wind.mp3" /var/lib/mpd/music/SDCARD/"Christopher Cross"
mkdir -p /var/lib/mpd/music/SDCARD/"Sia"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Sia"/"Sia - Chandelier.mp3" /var/lib/mpd/music/SDCARD/"Sia"
mkdir -p /var/lib/mpd/music/SDCARD/"Kanye West"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Kanye West"/"Kanye West - Heartless.mp3" /var/lib/mpd/music/SDCARD/"Kanye West"
mkdir -p /var/lib/mpd/music/SDCARD/"ZEDD"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"ZEDD"/"Zedd - Stay.mp3" /var/lib/mpd/music/SDCARD/"ZEDD"
mkdir -p /var/lib/mpd/music/SDCARD/"Benny Mardones"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Benny Mardones"/"Benny Mardones - Into The Night.mp3" /var/lib/mpd/music/SDCARD/"Benny Mardones"
mkdir -p /var/lib/mpd/music/SDCARD/"Robin Thicke"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Robin Thicke"/"Robin Thicke - Blurred Lines.mp3" /var/lib/mpd/music/SDCARD/"Robin Thicke"
mkdir -p /var/lib/mpd/music/SDCARD/"The Police"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Police"/"The Police - Wrapped Around Your Finger.mp3" /var/lib/mpd/music/SDCARD/"The Police"
mkdir -p /var/lib/mpd/music/SDCARD/"The Chainsmokers"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Chainsmokers"/"The Chainsmokers - Something Just Like This.mp3" /var/lib/mpd/music/SDCARD/"The Chainsmokers"
mkdir -p /var/lib/mpd/music/SDCARD/"Halsey"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Halsey"/"Halsey - Now Or Never.mp3" /var/lib/mpd/music/SDCARD/"Halsey"
mkdir -p /var/lib/mpd/music/SDCARD/"Jon Bellion"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Jon Bellion"/"Jon Bellion - All Time Low.mp3" /var/lib/mpd/music/SDCARD/"Jon Bellion"
mkdir -p /var/lib/mpd/music/SDCARD/"Ambrosia"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Ambrosia"/"Ambrosia - How Much I Feel.mp3" /var/lib/mpd/music/SDCARD/"Ambrosia"
mkdir -p /var/lib/mpd/music/SDCARD/"Ambrosia"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Ambrosia"/"Ambrosia - Biggest Part Of Me.mp3" /var/lib/mpd/music/SDCARD/"Ambrosia"
mkdir -p /var/lib/mpd/music/SDCARD/"Player"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Player"/"Player - Baby Come Back.mp3" /var/lib/mpd/music/SDCARD/"Player"
mkdir -p /var/lib/mpd/music/SDCARD/"Justin Bieber"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Justin Bieber"/"Justin Bieber - All That Matters.mp3" /var/lib/mpd/music/SDCARD/"Justin Bieber"
mkdir -p /var/lib/mpd/music/SDCARD/"10cc"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"10cc"/"10cc - I'm Not in Love.mp3" /var/lib/mpd/music/SDCARD/"10cc"
mkdir -p /var/lib/mpd/music/SDCARD/"Lane 8"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Lane 8"/"Lane 8 feat. Solomon Grey - Diamonds.mp3" /var/lib/mpd/music/SDCARD/"Lane 8"
mkdir -p /var/lib/mpd/music/SDCARD/"Live"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Live"/"Live - Lightning Crashes.mp3" /var/lib/mpd/music/SDCARD/"Live"
mkdir -p /var/lib/mpd/music/SDCARD/"Radiohead"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Radiohead"/"Radiohead - No Surprises.mp3" /var/lib/mpd/music/SDCARD/"Radiohead"
mkdir -p /var/lib/mpd/music/SDCARD/"Radiohead"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Radiohead"/"Radiohead - Paranoid Android.mp3" /var/lib/mpd/music/SDCARD/"Radiohead"
mkdir -p /var/lib/mpd/music/SDCARD/"Radiohead"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Radiohead"/"Radiohead - Airbag.mp3" /var/lib/mpd/music/SDCARD/"Radiohead"
mkdir -p /var/lib/mpd/music/SDCARD/"Radiohead"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Radiohead"/"Radiohead - Karma Police.mp3" /var/lib/mpd/music/SDCARD/"Radiohead"
mkdir -p /var/lib/mpd/music/SDCARD/"Kiesza"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Kiesza"/"Kiesza - Hideaway.mp3" /var/lib/mpd/music/SDCARD/"Kiesza"
mkdir -p /var/lib/mpd/music/SDCARD/"Christina Perri"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Christina Perri"/"Christina Perri-A Thousand Years.mp3" /var/lib/mpd/music/SDCARD/"Christina Perri"
mkdir -p /var/lib/mpd/music/SDCARD/"Trey Songz"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Trey Songz"/"Trey Songz - Touchin, Lovin (Feat. Nicki Minaj).mp3" /var/lib/mpd/music/SDCARD/"Trey Songz"
mkdir -p /var/lib/mpd/music/SDCARD/"Nick Jonas"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Nick Jonas"/"Nick Jonas - Jealous.mp3" /var/lib/mpd/music/SDCARD/"Nick Jonas"
mkdir -p /var/lib/mpd/music/SDCARD/"Milky Chance"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Milky Chance"/"Milky Chance - Stolen Dance.mp3" /var/lib/mpd/music/SDCARD/"Milky Chance"
mkdir -p /var/lib/mpd/music/SDCARD/"Sam Smith"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Sam Smith"/"Sam Smith - Stay With Me.mp3" /var/lib/mpd/music/SDCARD/"Sam Smith"
mkdir -p /var/lib/mpd/music/SDCARD/"Radiohead"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Radiohead"/"Radiohead - Creep.mp3" /var/lib/mpd/music/SDCARD/"Radiohead"
mkdir -p /var/lib/mpd/music/SDCARD/"Simple Minds"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Simple Minds"/"Simple Minds - Don't You Forget About Me.mp3" /var/lib/mpd/music/SDCARD/"Simple Minds"
mkdir -p /var/lib/mpd/music/SDCARD/"John Waite"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"John Waite"/"John Waite - Missing You (Newly Re-Recorded).mp3" /var/lib/mpd/music/SDCARD/"John Waite"
mkdir -p /var/lib/mpd/music/SDCARD/"Christopher Cross"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Christopher Cross"/"Christopher Cross - Sailing.mp3" /var/lib/mpd/music/SDCARD/"Christopher Cross"
mkdir -p /var/lib/mpd/music/SDCARD/"Katy Perry"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Katy Perry"/"Katy Perry - Dark Horse (feat. Juicy J).mp3" /var/lib/mpd/music/SDCARD/"Katy Perry"
mkdir -p /var/lib/mpd/music/SDCARD/"Level 42"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Level 42"/"Level 42 - Something About You.mp3" /var/lib/mpd/music/SDCARD/"Level 42"
mkdir -p /var/lib/mpd/music/SDCARD/"Erasure"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Erasure"/"Erasure - A Little Respect.mp3" /var/lib/mpd/music/SDCARD/"Erasure"
mkdir -p /var/lib/mpd/music/SDCARD/"Smokey Robinson"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Smokey Robinson"/"Smokey Robinson - Being With You.mp3" /var/lib/mpd/music/SDCARD/"Smokey Robinson"
mkdir -p /var/lib/mpd/music/SDCARD/"Lizzo"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Lizzo"/"Lizzo - Truth Hurts.mp3" /var/lib/mpd/music/SDCARD/"Lizzo"
mkdir -p /var/lib/mpd/music/SDCARD/"Halsey,Louis Bell"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Halsey,Louis Bell"/"Halsey,Louis Bell - Without Me.mp3" /var/lib/mpd/music/SDCARD/"Halsey,Louis Bell"
mkdir -p /var/lib/mpd/music/SDCARD/"Taylor Swift"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Taylor Swift"/"Taylor Swift - Lover.mp3" /var/lib/mpd/music/SDCARD/"Taylor Swift"
mkdir -p /var/lib/mpd/music/SDCARD/"Shaed"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Shaed"/"Shaed - Trampoline.mp3" /var/lib/mpd/music/SDCARD/"Shaed"
mkdir -p /var/lib/mpd/music/SDCARD/"Shawn Mendes"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Shawn Mendes"/"Shawn Mendes - Señorita.mp3" /var/lib/mpd/music/SDCARD/"Shawn Mendes"
mkdir -p /var/lib/mpd/music/SDCARD/"Taylor Swift"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Taylor Swift"/"Taylor Swift - You Need To Calm Down.mp3" /var/lib/mpd/music/SDCARD/"Taylor Swift"
mkdir -p /var/lib/mpd/music/SDCARD/"Kenny Loggins"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Kenny Loggins"/"Kenny Loggins - This Is It.mp3" /var/lib/mpd/music/SDCARD/"Kenny Loggins"
mkdir -p /var/lib/mpd/music/SDCARD/"Post Malone"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Post Malone"/"Post Malone - Circles.mp3" /var/lib/mpd/music/SDCARD/"Post Malone"
mkdir -p /var/lib/mpd/music/SDCARD/"Carly Simon"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Carly Simon"/"Carly Simon - You're So Vain.mp3" /var/lib/mpd/music/SDCARD/"Carly Simon"
mkdir -p /var/lib/mpd/music/SDCARD/"Pablo Cruise"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Pablo Cruise"/"Pablo Cruise - Love Will Find A Way.mp3" /var/lib/mpd/music/SDCARD/"Pablo Cruise"
mkdir -p /var/lib/mpd/music/SDCARD/"Rupert Holmes"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Rupert Holmes"/"Rupert Holmes - 70_s Pop Number 1_s(016)Escape.mp3" /var/lib/mpd/music/SDCARD/"Rupert Holmes"
mkdir -p /var/lib/mpd/music/SDCARD/"Jimmy Buffett"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Jimmy Buffett"/"Jimmy Buffett - Margaritaville.mp3" /var/lib/mpd/music/SDCARD/"Jimmy Buffett"
mkdir -p /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Doobie Brothers"/"The Doobie Brothers - Listen to the Music.mp3" /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
mkdir -p /var/lib/mpd/music/SDCARD/"Jonas Brothers"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Jonas Brothers"/"Jonas Brothers - Sucker.mp3" /var/lib/mpd/music/SDCARD/"Jonas Brothers"
mkdir -p /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Doobie Brothers"/"The Doobie Brothers - Minute by Minute.mp3" /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
mkdir -p /var/lib/mpd/music/SDCARD/"A Great Big World"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"A Great Big World"/"A Great Big World - Say Something.mp3" /var/lib/mpd/music/SDCARD/"A Great Big World"
mkdir -p /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"The Doobie Brothers"/"The Doobie Brothers - What a Fool Believes.flac" /var/lib/mpd/music/SDCARD/"The Doobie Brothers"
mkdir -p /var/lib/mpd/music/SDCARD/"Chicago"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Chicago"/"Chicago - If You Leave Me Now.mp3" /var/lib/mpd/music/SDCARD/"Chicago"
mkdir -p /var/lib/mpd/music/SDCARD/"Duran Duran"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Duran Duran"/"Duran Duran - Skin Trade.mp3" /var/lib/mpd/music/SDCARD/"Duran Duran"
mkdir -p /var/lib/mpd/music/SDCARD/"Gin Blossoms"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Gin Blossoms"/"Gin Blossoms - Hey Jealousy.mp3" /var/lib/mpd/music/SDCARD/"Gin Blossoms"
mkdir -p /var/lib/mpd/music/SDCARD/"Duran Duran"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Duran Duran"/"Duran Duran - Save a Prayer.mp3" /var/lib/mpd/music/SDCARD/"Duran Duran"
mkdir -p /var/lib/mpd/music/SDCARD/"Elvis Costello"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Elvis Costello"/"Elvis Costello - Allison.mp3" /var/lib/mpd/music/SDCARD/"Elvis Costello"
mkdir -p /var/lib/mpd/music/SDCARD/"Mark Morrison"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Mark Morrison"/"Mark Morrison - Return of the mack.mp3" /var/lib/mpd/music/SDCARD/"Mark Morrison"
mkdir -p /var/lib/mpd/music/SDCARD/"Dua Lipa"
cp /var/lib/mpd/music/NAS/Spiderman-POP/"Dua Lipa"/"Dua Lipa - Cold Heart.mp3" /var/lib/mpd/music/SDCARD/"Dua Lipa"
